export const ACTION_TYPE_FETCH_CANDIDATES_REQUEST = "ACACTION_TYPE_FETCH_CANDIDATES_REQUEST";

export const ACTION_TYPE_FETCH_CANDIDATES_SUCCESS = "ACTION_TYPE_FETCH_CANDIDATES_SUCCESS";

export const ACTION_TYPE_FETCH_CANDIDATES_FAILURE = "ACTION_TYPE_FETCH_CANDIDATES_FAILURE";

export const ACTION_TYPE_GET_CANDIDATE_DETAIL = "ACTION_TYPE_GET_CANDIDATE_DETAIL";

export const ACTION_TYPE_CLEAR_CANDIDATE_DETAIL = "ACTION_TYPE_CLEAR_CANDIDATE_DETAIL";